# Configuration for lava launcher by Ricardo Steijn

global-settings
{
	watch-config-file 		=true;
}

bar
{
	# Bar on right monitor
	size				=63;
	position			=bottom;
	margin 				=2;
	border 				= 1;
	background-colour		="#222222aa";
	border-colour = "#373633ff";
	alignment 			=center;
	exclusive-zone 			=false;
	indicator-style 		=rounded-rectangle;
	indicator-padding = 3;
	indicator-hover-colour = "#ffffff44";
	indicator-active-colour = "#ffffffaa";
	icon-padding = 8;
	layer = top;
	radius = 30;
	hidden-mode = always;
	hidden-size = 1;
	mode = default;
	exclusive-zone = stationary;




	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps@2x/scalable/terminal.svg;
		command			=kitty;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps@2x/scalable/file-manager.svg;
		command			= nautilus /;
	}

    spacer {
        length = 13;
    }

	button
	{
		image-path		= /home/glebkiva/.local/share/icons/Colloid/apps@2x/scalable/zed.svg;
		command			= ~/.local/bin/zed;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/webstorm.svg;
		command			= webstorm;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/clion.svg;
		command			= clion;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/idea.svg;
		command			= idea;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/studio.svg;
		command			= studio;
	}

	    spacer {
        length = 13;
    }

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/onlyoffice.svg;
		command			= flatpak run org.onlyoffice.desktopeditors;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/obsidian.svg;
		command			= flatpak run md.obsidian.Obsidian;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/anki.svg;
		command			= flatpak run net.ankiweb.Anki;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/notepad-48.svg;
		command			= flatpak run com.github.flxzt.rnote;
	}


	    spacer {
        length = 13;
    }


	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/agenda.svg;
		command			= flatpak run io.github.alainm23.planify;
	}
	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/com.rafaelmardojai.Blanket.svg;
		command			= flatpak run com.rafaelmardojai.Blanket;
	}

    button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/app.zen_browser.zen.svg;
		command			= flatpak run app.zen_browser.zen;
	}

    spacer {
        length = 13;
    }

    button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps@2x/scalable/chess.svg;
		command			= flatpak run org.chromium.Chromium --app-id=pdihgkikjgccndbckbcgjmcnpkockcjg;
	}
    button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps@2x/scalable/steam.svg;
		command			= steam;
	}
	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/letterboxd.svg;
		command			= flatpak run org.chromium.Chromium --app-id=llbabmcmhpkeogkmhghgnoacceamfipc;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/com.github.mohelm97.screenrecorder.svg;
		command			= flatpak run org.chromium.Chromium --app-id=agjjnlobpiaocbmpcpimcmohidjfheli;
	}
	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/chrome-cnmnfnkedfekfidgojcdmndbcipagogc-Default.svg;
		command			= flatpak run io.gitlab.news_flash.NewsFlash;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps/scalable/bookreader.svg;
		command			= flatpak run com.github.johnfactotum.Foliate;
	}

	button
	{
		image-path 		=/home/glebkiva/.local/share/icons/Colloid/apps@2x/scalable/telegram.svg;
		command			=flatpak run org.telegram.desktop;
	}


}
